using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MovementPacketGeneratorMOP
{
    public enum MovementStatusElements
    {
        // Bits
        MSEHasRemoveForcesIDs,
        MSEHasGuidByte0,
        MSEHasGuidByte1,
        MSEHasGuidByte2,
        MSEHasGuidByte3,
        MSEHasGuidByte4,
        MSEHasGuidByte5,
        MSEHasGuidByte6,
        MSEHasGuidByte7,
        MSEHasMovementFlags,
        MSEHasMovementFlags2,
        MSEHasMoveTime,
        MSEHasOrientation,
        MSEHasTransportData,
        MSEHasTransportGuidByte0,
        MSEHasTransportGuidByte1,
        MSEHasTransportGuidByte2,
        MSEHasTransportGuidByte3,
        MSEHasTransportGuidByte4,
        MSEHasTransportGuidByte5,
        MSEHasTransportGuidByte6,
        MSEHasTransportGuidByte7,
        MSEHasTransportTime2,
        MSEHasVehicleId,
        MSEHasPitch,
        MSEHasFallData,
        MSEHasFallDirection,
        MSEHasSplineElevation,
        MSEHasSpline,
        MSEHasMoveIdx,
        MSEHeightChangeFailed,
        MSERemoteTimeValid,

        // Values
        MSEGuidByte0,
        MSEGuidByte1,
        MSEGuidByte2,
        MSEGuidByte3,
        MSEGuidByte4,
        MSEGuidByte5,
        MSEGuidByte6,
        MSEGuidByte7,
        MSEMovementFlags,
        MSEMovementFlags2,
        MSEMoveTime,
        MSEPositionX,
        MSEPositionY,
        MSEPositionZ,
        MSEOrientation,
        MSETransportGuidByte0,
        MSETransportGuidByte1,
        MSETransportGuidByte2,
        MSETransportGuidByte3,
        MSETransportGuidByte4,
        MSETransportGuidByte5,
        MSETransportGuidByte6,
        MSETransportGuidByte7,
        MSETransportPositionX,
        MSETransportPositionY,
        MSETransportPositionZ,
        MSETransportOrientation,
        MSETransportSeat,
        MSETransportTime,
        MSETransportTime2,
        MSETransportVehicleId,
        MSEPitch,
        MSEFallTime,
        MSEFallVerticalSpeed,
        MSEFallCosAngle,
        MSEFallSinAngle,
        MSEFallHorizontalSpeed,
        MSESplineElevation,
        MSERemoveForcesIDs,
        MSEMoveIdx,
        MSESequenceIndex,
        MSESplineID,
        MSESpeed,
        MSEAckIndex,
        MSEMountDisplayID,
        MSEReason,
        MSEHeight,
        MSEEnd,
    };

}
